### PR TITLE
Typo: faling=> failing

### PR DESCRIPTION
**Pull request by jonathancross**
Funny rant  :-)

### CODE REVIEW

**Comment by jonathancross** [comment]
Hi @TheBlueMatt, any chance this will get merged?

**Comment by TheBlueMatt** [comment]
Oops, sorry.... Anyway, this repo is unmaintained (since Bitcoin Core has much better testing infrastructure now)... You might upstream it to BitcoinJ, though it may be better to just remove it there.....

**Comment by jonathancross** [comment]
BitcoinJ is already fixed: https://github.com/bitcoinj/bitcoinj/pull/1299 :-)

I came across some [links to your version](https://www.google.ch/#q=in-link:https://github.com/TheBlueMatt/test-scripts/blob/master/FullBlockTestGenerator.java&filter=0), so I thought I'd do it here as well.

**Comment by jonathancross** [comment]
Giving up.

**Pull request merged**
